/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yue_kyle_forndk_TestJni1 */

#ifndef _Included_com_yue_kyle_forndk_TestJni1
#define _Included_com_yue_kyle_forndk_TestJni1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yue_kyle_forndk_TestJni1
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yue_kyle_forndk_TestJni1_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_yue_kyle_forndk_TestJni1
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yue_kyle_forndk_TestJni1_plus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
